spring:
  data:
    mongodb:
      username: dhiraj
      password: dhiraj
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-server: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.coffee.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.coffee.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: dhiraj
    password: dhiraj
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connection-time-out: 5000
        time-out: 3000
        write-time-out: 5000
  server:
    port: 8040