spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payment
    username: dhiraj
    password: dhiraj
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.coffee.ecommerce.notification.PaymentNotificationRequest
  server:
    port: 8060

